const { connect } = require('./browser.cjs');
const assert = require('node:assert/strict');
(async () => {
  const b = await connect();
  const click = text => b.evaluate(`(()=>{const button=[...document.querySelectorAll('button')].find(item=>item.textContent.trim()===${JSON.stringify(text)});if(!button)throw new Error('Button not found: '+${JSON.stringify(text)});button.click()})()`);
  const setInput = (selector, value) => b.evaluate(`(()=>{const input=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(value)});input.dispatchEvent(new Event('input',{bubbles:true}))})()`);
  const inputValue = selector => b.evaluate(`document.querySelector(${JSON.stringify(selector)}).value`);
  const selectRole = role => b.evaluate(`(()=>{const select=document.querySelector('[aria-label="Workspace role"]');select.value=${JSON.stringify(role)};select.dispatchEvent(new Event('change',{bubbles:true}))})()`);
  const closeDialog = async () => { await b.evaluate(`document.querySelector('[role="dialog"] button[data-slot="dialog-close"]')?.click()`); await b.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape', windowsVirtualKeyCode: 27 }); await b.until('!document.querySelector(\'[role="dialog"]\')'); };
  try {
    await b.send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
    await b.send('Page.navigate', { url: 'http://127.0.0.1:4174/hosted/app/index.html?hostToken=test' });
    await b.until("document.querySelector('.bp-login-card')");
    await b.evaluate("Object.keys(localStorage).filter(key=>key.startsWith('buildpay-')).forEach(key=>localStorage.removeItem(key))");
    await click('Enter workspace');
    await b.until("document.querySelectorAll('.bp-table tbody tr').length===3");
    assert.equal(await b.evaluate('window.scrollY'), 0);
    assert.equal(await b.evaluate('location.search'), '?hostToken=test');
    assert.equal(await b.evaluate("document.querySelector('.bp-stat > strong').textContent"), '12');
    await b.screenshot('overview-fixtures-desktop');
    await click('PA-2026-001'); await b.until("document.querySelector('[role=dialog]')");
    console.log('APPROVER DIALOG', await b.evaluate("document.querySelector('[role=dialog]').innerText"));
    await closeDialog();
    await click('Application register');
    await b.until("document.querySelector('[aria-label=\"Search applications\"]')");
    assert.equal(await b.evaluate("document.querySelectorAll('.bp-table tbody tr').length"), 10);
    await click('Next'); assert.equal(await b.evaluate("document.querySelectorAll('.bp-table tbody tr').length"), 2);
    await b.evaluate(`(()=>{const input=document.querySelector('[aria-label="Search applications"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Northbank');input.dispatchEvent(new Event('input',{bubbles:true}))})()`);
    await b.until("document.querySelectorAll('.bp-table tbody tr').length===6");
    await b.evaluate(`(()=>{const select=document.querySelector('[aria-label="Filter by status"]');select.value='Recommended';select.dispatchEvent(new Event('change',{bubbles:true}))})()`);
    await b.until("document.querySelectorAll('.bp-table tbody tr').length===2");
    await click('Clear'); await b.until("document.querySelectorAll('.bp-table tbody tr').length===10");
    await selectRole('submitter'); await b.until("document.querySelector('.bp-count')?.textContent==='2 pending'");
    await click('New application'); await b.until("document.querySelector('[role=dialog]')");
    console.log('CREATE DIALOG', (await b.evaluate("document.querySelector('[role=dialog]').innerText")).slice(0, 1500));
    await setInput('[placeholder="Enter project name or code"]', 'test3333');
    await setInput('[placeholder="Enter contractor name"]', 'Sample Contractor');
    assert.equal(await inputValue('[placeholder="Enter contractor name"]'), 'Sample Contractor', 'Unmatched contractor text remains editable');
    await setInput('[placeholder="Enter project name or code"]', 'Meridian Business Park');
    await setInput('[placeholder="Enter contractor name"]', 'Peninsular Engineering');
    await setInput('[placeholder="Enter contract number"]', 'CON-001');
    await setInput('[placeholder="Enter package code"]', 'PKG-001');
    for (const [placeholder, expected] of [['Enter contractor name', 'Peninsular Engineering'], ['Enter contract number', 'CON-001'], ['Enter package code', 'PKG-001']]) {
      assert.equal(await inputValue(`[placeholder="${placeholder}"]`), expected, `${placeholder} retains typed text`);
    }
    await closeDialog();
    await selectRole('reviewer'); await b.until("document.querySelector('.bp-count')?.textContent==='3 pending'");
    await click('PA-2026-003'); await b.until("document.querySelector('[role=dialog]')");
    console.log('REVIEW DIALOG', (await b.evaluate("document.querySelector('[role=dialog]').innerText")).slice(0, 400));
    await closeDialog();
    await selectRole('finance'); await b.until("document.querySelector('.bp-count')?.textContent==='2 pending'");
    await click('PA-2026-005'); await b.until("document.querySelector('[role=dialog]')");
    assert.equal(await b.evaluate("document.querySelector('#gross').value"), '110000');
    console.log('FINANCE DIALOG', (await b.evaluate("document.querySelector('[role=dialog]').innerText")).slice(0, 1500));
    await closeDialog();
    await b.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
    await selectRole('approver'); await b.until("document.querySelector('.bp-count')?.textContent==='3 pending'");
    assert.ok(await b.evaluate('document.documentElement.scrollWidth <= innerWidth'));
    await b.until("document.querySelector('.bp-sidebar').getBoundingClientRect().right<=0.1");
    await b.screenshot('overview-mobile');
    await b.evaluate("document.querySelector('[aria-label=\"Open navigation\"]').click()");
    await b.until("document.querySelector('.bp-sidebar.is-open')"); await click('Workflow guide');
    await b.until("document.querySelector('.bp-guide-grid')");
    assert.ok(await b.evaluate('document.documentElement.scrollWidth <= innerWidth'));
    await b.evaluate("window.__bpTest.fail=true;window.__bpTest.queryClient.invalidateQueries({queryKey:['paymentApplication-list']})");
    await selectRole('approver');
    await b.until("document.querySelector('[role=alert]')");
    await b.evaluate('window.__bpTest.fail=false'); await click('Try again');
    await b.until("document.querySelector('.bp-count')?.textContent==='3 pending'");
    await b.evaluate("document.querySelector('[aria-label=\"Leave workspace\"]').click()");
    await b.until("document.querySelector('.bp-login-card')"); await b.screenshot('login-mobile');
    assert.ok(await b.evaluate('document.documentElement.scrollWidth <= innerWidth'));
    assert.equal(b.errors.length, 0, JSON.stringify(b.errors));
    console.log('PASS: role queues, all four dialogs, search, filters, pagination, host URL preservation, mobile navigation, failure recovery, sign out, and zero runtime exceptions.');
  } finally { b.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
